name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dd33592b6220ddf49a9b69e8b78bdd46917f890884790cf1ae1a9cafe425bf7"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
