name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d480326f4c2ae1521ca746b5310b65f2a961322f10e0d175e4aab9bdd15a0df0"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
