name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2b687fb020ed68df97e73d37942c888b93ff65b179d64a1aa5ffa3c9a4bb638"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
