name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35e1417f07bdae0ff86472f64abc0daa80b274c4f6110d82ee23f385e0068a7c"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
