name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff0ac0f5603dfe7bac902231a5589cb5a8a771fa51349e89861f3ccd115a82f0"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
