name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f9246ab5b0cad6e7c7114209323fa04c2aecb0ecf4c0f09ac402287ea8972ff"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
