name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ade0f4eca7662170ef03c4147a4b27aee6acf32a9677ec0b63862d0d1800cb5e"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
