name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22a0148bccc2127422c9948b5ae45a2cc59aeb9b3a83cd578515799f355e3380"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
