name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3241e70d9b913d6a1f8c61e886f1b32cf9dd3c8a06fcfc7d9f159c914193aa6f"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
