name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe39949b79da8275773e59a5104ca6836ab39840516808bc811ae28d3aa2de8b"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
