name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a48d6d8c279bd369dd57e8cc9be0da9621f8b0b76dd5b4867e0c806ff6308f1"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
