name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f08751ef98fef669c5fa9284d4791bb4a847305511416f9b02252fe366604ef"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
