name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ebde2b9da727ffcd2711fac72dce58b6abee915b191a7a5e82fca26cfee25b4"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
