name = "PEAK"
author = "Pepper"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcd387607fb31890bdc80574c9fc0a760d8a8c1410e07bdef10617ba1c626143"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
