# Don't change this! Version used to track needed updates.
version = 0
axeStripParticles = true
axeScrapeParticlesDisplayType = "DEFAULT"
axeWaxOffParticlesDisplayType = "DEFAULT"
boneMealUsingParticles = true
flintAndSteelParticles = true
increasedItemBreakParticles = false
waterEvaporateFromBucketSteam = true
waterBucketUseParticles = true
lavaBucketUseParticles = true
powderSnowBucketUseParticles = true